#ifndef SIGNALTYPE_H
#define SIGNALTYPE_H

#include <iostream>

enum SignalType : uint16_t
{
    NONE = 0,
    STATUS_NEXTWORK = 1000,
    STATUS_WIFI,
    STATUS_FIREBASE,
    STATUS_NTP,
    WIFI_SUCCESSFULL,
    WIFI_FAILED,
    FIREBASE_SUCCESSFULL,
    FIREBASE_FAILED,
    NTP_SUCCESSFULL,
    NTP_FAILED,

    CONNECT_WIFI_SUCCESSFULL,
    CONNECT_WIFI_FAILED,
    CONNECT_FIREBASE_SUCCESSFULL,
    CONNECT_FIREBASE_FAILED,
    CONNECT_NTP_SUCCESSFULL,
    CONNECT_NTP_FAILED,
    CONNECT_RETRY,

    CHECK_COMMAND_FIREBASE,
    WEB_GET_ALLTIME_DATA_REQUEST,
    WEB_GET_ALLTIME_DATA_RESPONSE,
    WEB_SET_ALLTIME_DATA_REQUEST,
    WEB_SET_ALLTIME_DATA_RESPONSE,

    WEB_GET_LIGHT1_DATA_REQUEST,
    WEB_GET_LIGHT1_DATA_RESPONSE,
    WEB_SET_LIGHT1_DATA_REQUEST,
    WEB_SET_LIGHT1_DATA_RESPONSE,

    WEB_GET_LIGHT2_DATA_REQUEST,
    WEB_GET_LIGHT2_DATA_RESPONSE,
    WEB_SET_LIGHT2_DATA_REQUEST,
    WEB_SET_LIGHT2_DATA_RESPONSE,

    WEB_GET_LIGHT3_DATA_REQUEST,
    WEB_GET_LIGHT3_DATA_RESPONSE,
    WEB_SET_LIGHT3_DATA_REQUEST,
    WEB_SET_LIGHT3_DATA_RESPONSE,

    WEB_GET_LIGHT4_DATA_REQUEST,
    WEB_GET_LIGHT4_DATA_RESPONSE,
    WEB_SET_LIGHT4_DATA_REQUEST,
    WEB_SET_LIGHT4_DATA_RESPONSE,

    WEB_GET_STATUS_DATA_REQUEST,
    WEB_GET_STATUS_DATA_RESPONSE,
    WEB_SET_STATUS_LIGHT1_DATA_REQUEST,
    WEB_SET_STATUS_LIGHT2_DATA_REQUEST,
    WEB_SET_STATUS_LIGHT3_DATA_REQUEST,
    WEB_SET_STATUS_LIGHT4_DATA_REQUEST,
    WEB_SET_STATUS_LIGHT_DATA_RESPONSE,

    REMOTE_LIGHT_GET_TIME_DATE_FROM_NTP,
    REMOTE_LIGHT_SEND_TIME_DATE_FROM_NTP,
};

#endif // SIGNALTYPE_H