#ifndef SIGNALTYPE_H
#define SIGNALTYPE_H

#include <iostream>

enum SignalType : uint16_t
{
    NONE = 0,
    STATUS_NEXTWORK = 1000,
    STATUS_WIFI,
    STATUS_FIREBASE,
    STATUS_NTP,

    CONNECT_WIFI_SUCCESSFULL,
    CONNECT_WIFI_FAILED,
    CONNECT_FIREBASE_SUCCESSFULL,
    CONNECT_FIREBASE_FAILED,
    CONNECT_NTP_SUCCESSFULL,
    CONNECT_NTP_FAILED,

    CHECK_COMMAND_FIREBASE,
    WEB_GET_ALLTIME_DATA_REQUEST,
    WEB_GET_ALLTIME_DATA_RESPONSE,

    WEB_SET_ALLTIME_DATA_REQUEST,
    WEB_SET_ALLTIME_DATA_RESPONSE,
};

#endif // SIGNALTYPE_H