#ifndef SIGNALTYPE_H
#define SIGNALTYPE_H

#include <iostream>

enum SignaLType : uint16_t
{
    NONE = 0,
    STATUS_NEXTWORK = 1000,
    STATUS_WIFI,
    STATUS_FIREBASE,
    STATUS_NTP,

    CONNECT_WIFI_SUCCESSFULL,
    CONNECT_WIFI_FAILED,
    CONNECT_FIREBASE_SUCCESSFULL,
    CONNECT_FIREBASE_FAILED,
    CONNECT_NTP_SUCCESSFULL,
    CONNECT_NTP_FAILED,
};

#endif // SIGNALTYPE_H